### PR TITLE
Fix Vite HMR

### PR DESCRIPTION
**Pull request by silviogutierrez**

### CODE REVIEW

**Comment by silviogutierrez** [comment]
@crgwbr : this is an oversight on my part, having major issues with HMR, even on the sample project. Looks like HMR after vite 5.0 acts up. Hopefully this downgrade fixes it.

I hope the move to 6.0 will skip these issues: https://github.com/vitejs/vite/issues/16284

Or maybe the Vite snippet injected into the page needs to be updated?

**Comment by crgwbr** [comment]
This is odd—I've been using these versions in my projects for a while and haven't seen any issues with HMR.

**Comment by silviogutierrez** [comment]
Just re-tried on the example project and it's definitely broken.

Look out for `page reload` instead of `hmr update` in the server output. Page reload might be fast enough to look like HMR, but it's not. You lose state, etc.

**Comment by crgwbr** [comment]
Right, don't doubt that—I meant our internal projects it's working fine. I wonder what the real trigger is.

**Comment by silviogutierrez** [comment]
My hunch is `vanilla-extract` and I'm guessing you don't use it. I believe it's broken HMR before.

**Comment by crgwbr** [comment]
That would make sense. We use CSS modules rather than vanilla extract. Personally I like VE, but our front-end devs were not having it 😛

**Comment by silviogutierrez** [comment]
Originally went with VE because it had less tooling than say, Linaria: https://github.com/silviogutierrez/reactivated/discussions/139

But now that I've tried tailwind, it's hard to go back. Even if you lose type safety. Colocation is just too good.

Will likely add built-in tailwind support in the future and get rid of VE. And explore panda CSS, which looks like linaria without any of the downsides.

**Pull request merged**
