### PR TITLE
Fix Nix symlink regression

### PR DESCRIPTION
**Pull request by silviogutierrez**

### CODE REVIEW

**Comment by allen-munsch** [comment]
Have any quick tips on how to try this particular branch? Got here because I was looking for something quick to deploy to fly.io and this project looks promising! Thank you!

Ubuntu 22.04, amd64

following the docs i got

```
Enter a project name
helloworld
ln: failed to create symbolic link 'helloworld/server/settings/__init__.py': No such file or directory
```

**Comment by silviogutierrez** [comment]
I thought this was fixed by https://github.com/silviogutierrez/reactivated/issues/369 ? Did you try the latest nix version?

**Comment by allen-munsch** [comment]
> I thought this was fixed by #369 ? Did you try the latest nix version?

So weirdly, when I did the curl install of nix, the "latest" version was likely installed?

`nix-2.24.9`

However, when I ran this to "upgrade" nix:

```
nix-channel --update; nix-env --install --attr nixpkgs.nix nixpkgs.cacert
```

I got a confusing "upgrade":

```
nix-channel --update; nix-env --install --attr nixpkgs.nix nixpkgs.cacert
unpacking 1 channels...
replacing old 'nix-2.24.9'
installing 'nix-2.18.8'
installing 'nss-cacert-3.101.1'
these 4 paths will be fetched (75.55 MiB download, 112.34 MiB unpacked):
  /nix/store/hady306s80zjl8avq98czpv0lg5dw5ad-nix-2.18.8-debug
  /nix/store/8n45k4i68vvql5mr6cks7yxj45v2z7k9-nix-2.18.8-doc
  /nix/store/0fk9dnrc8gg0dcmirsvp5v5v95h0xzkj-nss-cacert-3.101.1-p11kit
  /nix/store/bs3h8j1f65shkx6nmdpghwjkg0c8zqa2-nss-cacert-3.101.1-unbundled
```


Version `nix-2.18.8` appeared to work, might be because I'm using 22.04 which is starting to get a bit dated.

Thanks for the pointer.
All set

**Comment by silviogutierrez** [comment]
Great! Going to close this out. Ping me if you have any more issues or questions.

**Pull request closed without merging**
