### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by morenoh149**
* fixes https://github.com/silviogutierrez/reactivated/issues/16

### CODE REVIEW

**Comment by morenoh149** [comment]
I have read the CLA Document and I hereby sign the CLA. If applicable, I have secured permission from my employer.

**Comment by silviogutierrez** [comment]
recheck

**Comment by morenoh149** [comment]
recheck

**Comment by silviogutierrez** [comment]
@morenoh149 : I know this is a big pain for something so trivial. But it's actually related to this bug: https://github.com/contributor-assistant/github-action/issues/91

If you look at your raw commit here: https://github.com/morenoh149/reactivated/commit/b18c86fa90995739f60c2b6931dd32c0762e4109.patch

you can see the email in the commit does not match what's on your GitHub profile, so it has a hard time looking you up.

Try adding that email to your profile (you can have many) here: https://github.com/settings/emails and we'll recheck it. If you're willing of course. After that I'm willing to give up and just merge anyway. But it can help debug that CLA issue for the future.

Thanks again for your work.

**Comment by morenoh149** [comment]
moved https://github.com/silviogutierrez/reactivated/pull/239

**Pull request closed without merging**
