### PR TITLE
Fix setup for existing projects

### PR DESCRIPTION
**Pull request by silviogutierrez**

### CODE REVIEW

**Comment by SoRobby** [comment]
Please reference: 

- https://github.com/SoRobby/DjangoReactivated/tree/main/testproject01
- https://github.com/SoRobby/DjangoReactivated/tree/main/testproject02

The error message is the same in each project. The only difference between projectest01 and projectest01 is the method the node package reactivated is installed.

**Comment by silviogutierrez** [comment]
@SoRobby : thanks, I created a new release (0.24.0) that does not depend on `yarn`. I noticed in your repo projects you were installing `reactivated` from PyPi, which did *not* include the fixes on this branch. `0.24.0` should have those fixes. Give it a try.

**Comment by SoRobby** [comment]
@silviogutierrez I attempted to setup reactivated again. I made sure my python reactivated and npm reactivated versions were the same. I used v0.24.0 as specified. 

Test project here: https://github.com/SoRobby/DjangoReactivated/tree/main/testproject02

```
(django-reactivated) PS D:\Documents\GitHub\DjangoReactivated\DjangoReactivated\testproject02> python .\manage.py runserver
[13/Apr/2022 00:28:39,730] Generating interfaces and client side code
[13/Apr/2022 00:28:41,512] Finished generating.
Traceback (most recent call last):
  File "D:\Documents\GitHub\DjangoReactivated\DjangoReactivated\testproject02\manage.py", line 22, in <module>
    main()
  File "D:\Documents\GitHub\DjangoReactivated\DjangoReactivated\testproject02\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\commands\runserver.py", line 111, in handle
    self.run(**options)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\core\management\commands\runserver.py", line 118, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\django\utils\autoreload.py", line 682, in run_with_reloader
    exit_code = restart_with_reloader()
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\reactivated\__init__.py", line 47, in patched_restart_with_reloader
    processes.start_tsc()
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\site-packages\reactivated\processes.py", line 10, in start_tsc
    tsc_process = subprocess.Popen(
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\envs\django-reactivated\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by silviogutierrez** [comment]
I cloned your sample repo and had to make the following change, which I'll document:

Add `tsconfig.json` to `testproject02`:

```
{
    "compilerOptions": {
        "strict": true,
        "sourceMap": true,
        "noEmit": true,
        "module": "commonjs",
        "target": "es6",
        "esModuleInterop": true,
        "allowJs": true,
        "jsx": "react",
        "baseUrl": ".",
        "paths": {
            "@client/*": ["client/*"],
            "@reactivated": ["node_modules/_reactivated"]
        }
    },
    "include": ["./client/**/*"]
}
```

And try running it again. This worked on my machine, but I'm not on Windows.

**Pull request merged**
